os: Visual Studio 2015
version: 0.0.1.{build}

configuration:
- Debug
- Release

environment:
  BOOST_ROOT: C:\Libraries\boost_1_60_0

  matrix:
  #- VS_VERSION: 9 2008
  #  VS_PLATFORM: win32
  #  BOOST_LIBRARYDIR: C:\Libraries\boost_1_60_0\lib32-msvc-9.0
  #- VS_VERSION: 9 2008
  #  VS_PLATFORM: x64
  #  BOOST_LIBRARYDIR: C:\Libraries\boost_1_60_0\lib64-msvc-9.0
  #- VS_VERSION: 10 2010
  #  VS_PLATFORM: win32
  #  BOOST_LIBRARYDIR: C:\Libraries\boost_1_60_0\lib32-msvc-10.0
  #- VS_VERSION: 10 2010
  #  VS_PLATFORM: x64
  #  BOOST_LIBRARYDIR: C:\Libraries\boost_1_60_0\lib64-msvc-10.0
  #- VS_VERSION: 11 2012
  #  VS_PLATFORM: win32
  #  BOOST_LIBRARYDIR: C:\Libraries\boost_1_60_0\lib32-msvc-11.0
  #- VS_VERSION: 11 2012
  #  VS_PLATFORM: x64
  #  BOOST_LIBRARYDIR: C:\Libraries\boost_1_60_0\lib64-msvc-11.0
  #- VS_VERSION: 12 2013
  #  VS_PLATFORM: win32
  #  BOOST_LIBRARYDIR: C:\Libraries\boost_1_60_0\lib32-msvc-12.0
  #- VS_VERSION: 12 2013
  #  VS_PLATFORM: x64
  #  BOOST_LIBRARYDIR: C:\Libraries\boost_1_60_0\lib64-msvc-12.0
  #- VS_VERSION: 14 2015
  #  VS_PLATFORM: win32
  #  BOOST_LIBRARYDIR: C:\Libraries\boost_1_60_0\lib32-msvc-14.0
  - VS_VERSION: 14 2015
    VS_PLATFORM: x64
    BOOST_LIBRARYDIR: C:\Libraries\boost_1_60_0\lib64-msvc-14.0

before_build:
- cmake -DUSE_LOCAL_THIRD_PARTY_LIBRARY=OFF -H. -BBuild/VS -G "Visual Studio %VS_VERSION%" -DCMAKE_GENERATOR_PLATFORM=%VSPLATFORM% -DCMAKE_VERBOSE_MAKEFILE=ON -DBUILD_SHARED_LIBS=true -Wno-dev -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%"

build:
  project: Build\VS\BoostAsioPractice.sln
  parallel: true
  verbosity: minimal