os: Visual Studio 2015
version: 0.0.1.{build}

configuration:
- Debug
- Release

environment:
  BOOST_ROOT: C:\Libraries\boost_1_60_0
  BOOST_INCLUDEDIR: C:\Libraries\boost_1_60_0

  matrix:
  - VS_VERSION: 14 2015
    VS_PLATFORM: win32
    BOOST_LIBRARYDIR: C:\Libraries\boost_1_60_0\lib32-msvc-14.0
  - VS_VERSION: 14 2015 Win64
    VS_PLATFORM: x64
    BOOST_LIBRARYDIR: C:\Libraries\boost_1_60_0\lib64-msvc-14.0

install:
- ps: |
    $catchHeaderPath = "ThirdParty\Catch\catch.hpp""
    if (!(Test-Path $catchHeaderPath)) {
      $source = "https://raw.githubusercontent.com/philsquared/Catch/v1.5.6/single_include/catch.hpp"
      $destination = "c:\\projects\BoostAsioPractice\ThirdParty\Catch\catch.hpp"
      mkdir ThirdParty\Catch
      Invoke-WebRequest $source -OutFile $destination
    }
    

before_build:
- cmake -DUSE_LOCAL_THIRD_PARTY_LIBRARY=OFF -H. -BBuild/VS -G "Visual Studio %VS_VERSION%" -DCMAKE_GENERATOR_PLATFORM=%VSPLATFORM% -DCMAKE_VERBOSE_MAKEFILE=ON -DBUILD_SHARED_LIBS=true -Wno-dev -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_INCLUDEDIR="%BOOST_INCLUDEDIR%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%"

cache:
  - ThirdParty\Catch -> appveyor.yml

build:
  project: Build\VS\BoostAsioPractice.sln
  parallel: true
  verbosity: minimal

test_script:
- cd Build\VS
- ctest --verbose --build-config %CONFIGURATION%